Update arm image tag
c3os-io/c3os pull request #81
Opened 2022-08-10 22:18 UTC by dramich

2022-08-10 22:19 UTC, paynejacob approved these changes

2022-08-10 22:26 UTC, paynejacob approved these changes

2022-08-11 15:18 UTC, dramich commented
This PR should hold until the k3s stuff is moved out and we can verify the build succeeds

2022-08-15 14:46 UTC, mudler commented
Can you try current images from master? Images tagged with `latest` should be fine by now

2022-08-15 16:39 UTC, mudler requested changes

2022-08-15 16:39 UTC, mudler commented on .github/workflows/release-arm.yaml
> +          IMAGE: quay.io/c3os/c3os-${{ matrix.flavor }}:latest
I think this is not needed anymore there is a separate workflow pushing arm images now https://github.com/c3os-io/c3os/blob/b81e17ee026628a6cae70a6b0b1ff808145b99bf/.github/workflows/image-arm.yaml#L47

2022-08-16 20:03 UTC, closed without merging

2022-08-16 20:05 UTC, dramich commented
Closed in favor of https://github.com/c3os-io/c3os/pull/86